# Copyright (c) 2013 IndexData ApS. http://indexdata.com

all: jasmine-links

clean distclean:
	rm -rf test jasmine
	
jasmine-links:
	ln -fs ../../../jasmine .
	ln -fs ../../test .

help:
	@echo "make [ all | clean | jasmine-links ]"

